server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
  servlet:
    multipart:
      max-file-size: 1000MB
      enabled: 'true'
      max-request-size: 1000MB
  datasource:
    password:
    username: root
    url: jdbc:mysql://localhost:3306/dborder?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


